### ISSUE TITLE
Webpage improvement

### ISSUE THREAD

**Issue by sangkilc** [SoftSec-KAIST/MeanDiff#26]
Please fix the following issues before the ASE deadline.

- [x] Describe what the project is about. People should be able to know what the web page is about when they first visit the page.

- [x] The page currently has several tables, but it is not clear whether the table is about bugs found.

- [x] Clearly show the versions of each lifters we tested.

- [x] Have a link to our paper PDF and the source code.

**Comment by mfaerevaag** [comment]
All has been fixed. Please see [System section](https://softsec-kaist.github.io/MeanDiff/#system) review. Leaving this task unchecked for now.

**Comment by mfaerevaag** [comment]
A description has been pushed and is ready for review.

**Comment by sangkilc** [comment]
Good job!
